spring:
  profiles:
    active: "default"
  application:
    name: "${SPRING_APP_NAME:recommendation-service}"
  data:
    redis:
      host: "${REDIS_HOST:localhost}"
      port: "${REDIS_PORT:6379}"
      password: "${REDIS_PASSWORD:}"

logging:
  pattern:
    console: "${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"
management:

  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8088

microserviceUrls:
  auth-service: http://localhost:8080
  user-service: http://localhost:8081
  job-service: http://localhost:8082
  reservation-service: http://localhost:8083
  review-service: http://localhost:8084
  report-service: http://localhost:8085
  chat-service: http://localhost:8086
  notification-service: http://localhost:8087
  recommendation-service: http://localhost:8088
  payment-service: http://localhost:8089