apiVersion: v1
kind: Service
metadata:
  name: recommendation-service-service
  namespace: hah
spec:
  selector:
    app: recommendation-service
  ports:
    - name: gateway
      protocol: TCP
      port: 8088
  type: ClusterIP